### ISSUE TITLE
Remove sitemap line in robots.txt

### ISSUE THREAD

**Issue by laygir** [harlan-zw/nuxt-simple-robots#47]
### Details

Hi,
I would like to omit the `Sitemap` line in my robots.txt for a specific environment. But I noticed even doing the following results in an error on `nuxt generate` command. I understand from the [docs](https://nuxtseo.com/robots/api/config#sitemap) this should be possible. What am I missing 👀  

```js
// nuxt.config.js
robots: {
  sitemap: false,
},
```

**Comment by harlan-zw** [comment]
hi @laygir. It's not clear what the use case is, if you're trying to remove the sitemap as the environment isn't indexable, please see [Disabling Indexing](https://nuxtseo.com/robots/guides/disable-indexing).

Otherwise, you can achieve what you're trying to do by leveraging the [Nitro hooks](https://nuxtseo.com/robots/nitro-api/nitro-hooks).

```ts
// server/plugins/robots-remove-sitemap.ts
export default defineNitroPlugin((nitroApp) => {
  nitroApp.hooks.hook('robots:config', async (ctx) => {
    ctx.sitemaps = []
  })
})
```
